spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
