input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [app_name] {
    mutate {
      add_field => { "service" => "%{[app_name]}" }
    }
  }

  if [level] {
    mutate {
      uppercase => [ "level" ]
    }
  }

  if [@timestamp] {
    date {
      match => ["@timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }

  # Remove campos redundantes do logstash-logback-encoder
  mutate {
    remove_field => ["host", "port"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "decoder-logs-%{[app_name]}-%{+YYYY.MM.dd}"
    template_overwrite => false
  }
  stdout {
    codec => rubydebug { metadata => false }
  }
}
